spring.application.name=url-shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener_db
spring.datasource.username=avijit
spring.datasource.password=123456
spring.jpa.show-sql=true
server.port=8080


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
